[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/bitrix_widget.html"
  to = "/bitrix_widget.html"
  status = 200
  force = true
  conditions = {Method = ["POST"]}
