import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
  args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport:{width:1000,height:600} });
await p.addInitScript(()=>{ delete window.SpeechRecognition; delete window.webkitSpeechRecognition; });
let asked=null;
p.on('dialog', async d => { asked=d.message(); await d.accept('hello my name is sasha'); });
await p.goto('http://localhost:8642',{waitUntil:'load'});
await p.waitForTimeout(1000); await p.click('#spSolo');
await p.waitForFunction(()=>window.game&&window.game.ready(),null,{timeout:20000});
await p.evaluate(()=>{ window.game.setPaused(false); window.game.setDrag(true); });
await p.waitForTimeout(800);
await p.evaluate(()=>window.game.startLesson('starter-01'));
await p.waitForTimeout(1000);
await p.evaluate(()=>window.game.runStage(0));
await p.waitForTimeout(900);
console.log('кнопка:', await p.evaluate(()=>{const b=document.getElementById('sayBtn');
  return getComputedStyle(b).display+' | '+b.textContent;}));
await p.keyboard.press('r');
await p.waitForTimeout(1000);
console.log('диалог, открытый клавишей R:', JSON.stringify(asked));
console.log('задание засчитано:', await p.evaluate(()=>window.game.taskState().done));
await p.screenshot({path:'saykey.png'});
await b.close();
